# Generated by Django 2.1 on 2018-09-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=64)),
                ('host', models.ManyToManyField(to='CMDB.HostInfo')),
            ],
        ),
    ]
